#!/bin/bash

cd /mnt/tambinidata/sleepstudy/data/derivatives/group/ppi_os/
for areai in Post_L_Hipp Post_R_Hipp L_Caud R_Caud
	do
	fslmerge -t group_am-pm_${areai}_complete2V sub-105_am-pm_${areai}.nii.gz sub-106_am-pm_${areai}.nii.gz sub-108_am-pm_${areai}.nii.gz sub-111_am-pm_${areai}.nii.gz sub-112_am-pm_${areai}.nii.gz sub-113_am-pm_${areai}.nii.gz sub-114_am-pm_${areai}.nii.gz sub-115_am-pm_${areai}.nii.gz sub-116_am-pm_${areai}.nii.gz sub-118_am-pm_${areai}.nii.gz sub-121_am-pm_${areai}.nii.gz sub-123_am-pm_${areai}.nii.gz sub-124_am-pm_${areai}.nii.gz sub-125_am-pm_${areai}.nii.gz sub-126_am-pm_${areai}.nii.gz sub-127_am-pm_${areai}.nii.gz sub-130_am-pm_${areai}.nii.gz sub-131_am-pm_${areai}.nii.gz sub-132_am-pm_${areai}.nii.gz sub-133_am-pm_${areai}.nii.gz sub-135_am-pm_${areai}.nii.gz sub-136_am-pm_${areai}.nii.gz sub-137_am-pm_${areai}.nii.gz sub-138_am-pm_${areai}.nii.gz sub-142_am-pm_${areai}.nii.gz sub-144_am-pm_${areai}.nii.gz sub-148_am-pm_${areai}.nii.gz sub-149_am-pm_${areai}.nii.gz

	fslmerge -t group_allsessions_${areai}_complete2V sub-105_allsessions_${areai}.nii.gz sub-106_allsessions_${areai}.nii.gz sub-108_allsessions_${areai}.nii.gz sub-111_allsessions_${areai}.nii.gz sub-112_allsessions_${areai}.nii.gz sub-113_allsessions_${areai}.nii.gz sub-114_allsessions_${areai}.nii.gz sub-115_allsessions_${areai}.nii.gz sub-116_allsessions_${areai}.nii.gz sub-118_allsessions_${areai}.nii.gz sub-121_allsessions_${areai}.nii.gz sub-123_allsessions_${areai}.nii.gz sub-124_allsessions_${areai}.nii.gz sub-125_allsessions_${areai}.nii.gz sub-126_allsessions_${areai}.nii.gz sub-127_allsessions_${areai}.nii.gz sub-130_allsessions_${areai}.nii.gz sub-131_allsessions_${areai}.nii.gz sub-132_allsessions_${areai}.nii.gz sub-133_allsessions_${areai}.nii.gz sub-135_allsessions_${areai}.nii.gz sub-136_allsessions_${areai}.nii.gz sub-137_allsessions_${areai}.nii.gz sub-138_allsessions_${areai}.nii.gz sub-142_allsessions_${areai}.nii.gz sub-144_allsessions_${areai}.nii.gz sub-148_allsessions_${areai}.nii.gz sub-149_allsessions_${areai}.nii.gz

	fslmerge -t group_amaverage_${areai}_complete2V sub-105_amaverage_${areai}.nii.gz sub-106_amaverage_${areai}.nii.gz sub-108_amaverage_${areai}.nii.gz sub-111_amaverage_${areai}.nii.gz sub-112_amaverage_${areai}.nii.gz sub-113_amaverage_${areai}.nii.gz sub-114_amaverage_${areai}.nii.gz sub-115_amaverage_${areai}.nii.gz sub-116_amaverage_${areai}.nii.gz sub-118_amaverage_${areai}.nii.gz sub-121_amaverage_${areai}.nii.gz sub-123_amaverage_${areai}.nii.gz sub-124_amaverage_${areai}.nii.gz sub-125_amaverage_${areai}.nii.gz sub-126_amaverage_${areai}.nii.gz sub-127_amaverage_${areai}.nii.gz sub-130_amaverage_${areai}.nii.gz sub-131_amaverage_${areai}.nii.gz sub-132_amaverage_${areai}.nii.gz sub-133_amaverage_${areai}.nii.gz sub-135_amaverage_${areai}.nii.gz sub-136_amaverage_${areai}.nii.gz sub-137_amaverage_${areai}.nii.gz sub-138_amaverage_${areai}.nii.gz sub-142_amaverage_${areai}.nii.gz sub-144_amaverage_${areai}.nii.gz sub-148_amaverage_${areai}.nii.gz sub-149_amaverage_${areai}.nii.gz

	fslmerge -t group_pmaverage_${areai}_complete2V sub-105_pmaverage_${areai}.nii.gz sub-106_pmaverage_${areai}.nii.gz sub-108_pmaverage_${areai}.nii.gz sub-111_pmaverage_${areai}.nii.gz sub-112_pmaverage_${areai}.nii.gz sub-113_pmaverage_${areai}.nii.gz sub-114_pmaverage_${areai}.nii.gz sub-115_pmaverage_${areai}.nii.gz sub-116_pmaverage_${areai}.nii.gz sub-118_pmaverage_${areai}.nii.gz sub-121_pmaverage_${areai}.nii.gz sub-123_pmaverage_${areai}.nii.gz sub-124_pmaverage_${areai}.nii.gz sub-125_pmaverage_${areai}.nii.gz sub-126_pmaverage_${areai}.nii.gz sub-127_pmaverage_${areai}.nii.gz sub-130_pmaverage_${areai}.nii.gz sub-131_pmaverage_${areai}.nii.gz sub-132_pmaverage_${areai}.nii.gz sub-133_pmaverage_${areai}.nii.gz sub-135_pmaverage_${areai}.nii.gz sub-136_pmaverage_${areai}.nii.gz sub-137_pmaverage_${areai}.nii.gz sub-138_pmaverage_${areai}.nii.gz  sub-142_pmaverage_${areai}.nii.gz sub-144_pmaverage_${areai}.nii.gz sub-148_pmaverage_${areai}.nii.gz sub-149_pmaverage_${areai}.nii.gz

#create negative contrast
	fslmaths group_am-pm_${areai}_complete2V.nii.gz -mul -1 -nan group_am-pm_${areai}_complete2V_neg.nii
	fslmaths group_allsessions_${areai}_complete2V.nii.gz -mul -1 -nan group_allsessions_${areai}_complete2V_neg.nii
	fslmaths group_pmaverage_${areai}_complete2V.nii.gz -mul -1 -nan group_pmaverage_${areai}_complete2V_neg.nii
	fslmaths group_amaverage_${areai}_complete2V.nii.gz -mul -1 -nan group_amaverage_${areai}_complete2V_neg.nii
done 

